### ISSUE TITLE
Impact reactor power generation decrease when I exit the game

### ISSUE THREAD

**Issue by Feraferu** [sk7725/TimeControl#12]
On mobile, whenever I exit the game, the impact reactors on the map will decrease power generation. It messed up some of my sectors before I noticed it so I hope it could be fixed quickly.
Proof:
https://drive.google.com/file/d/119CRj-eZ9s6XFC2D2g7Nrm563GJLJTXL/view?usp=drivesdk

**Comment by sk7725** [comment]
Not a bug I can fix easily. In fact, I do not know if it is even timecontrol doing this.

**Comment by Feraferu** [comment]
I only use DeltaNedas/rtfm and if I disable TimeControl the bug disappears, so I'm sure it's TimeControl. I never seen anything about this so I'm not sure if anybody else experienced it though.

**Comment by sk7725** [comment]
Cannot reproduce nor fix.
