### ISSUE TITLE
Can enhance the code by adding linting and prettier. Also possible to add testings, CI

### ISSUE THREAD

**Issue by Niaz-Ul-Haque** [sk7725/TimeControl#4]
I am interested in contributing to this repo as a part of my coursework and self-practice. I am interested in add linting and prettier to this repo to keep the source code updated. if it's possible, please do assign me this issue. Also I can add testings/CI to the project.
Thank you!

**Comment by DeltaNedas** [comment]
describe your mindustry mod ci

**Comment by Niaz-Ul-Haque** [comment]
A week ago I learned about CI and implemented t on my personal CLI project (for automated testings when pushed). I wanted to strengthen my knowledge more on CI and testings by implementing it onto other open-source projects. I'll start looking at the code verbosely once you give me permission and assign me. I saw the code briefly and it felt like ill be able to implement the functionality I mentioned. Thank you!

**Comment by sample-text-here** [comment]
```sh
cd TimeControl
npm i -g prettier
nano .git/hooks/format.sh
# enter in the code below and save
chmod +x .git/hooks/format.sh
```
```sh
#!/bin/sh
#formats code on commit
prettier --write .
```
be warned: the first time you push with formatted code there will be chonky diffs because of all the new whitespace

**Comment by Niaz-Ul-Haque** [comment]
Ahh, noted. Tahnk you! Ill try my pest to get the best possible results and do a PR for a review. Thanks for the opportunity!

**Comment by Niaz-Ul-Haque** [comment]
Ahhh, Did a similar issue a few mins back. Sorry for getting things started here. I close this issue now. Thank you for the opportunity and very sorry.
