### ISSUE TITLE
Problem with author

### ISSUE THREAD

**Issue by Bohaska** [sk7725/TimeControl#8]
The owner of this mod has plagiarized several quotes of mine from a text without citing the original user of the text. Proof: PR https://github.com/Anuken/Mindustry/pull/3793 in Anuken/Mindustry

**Comment by sk7725** [comment]
Ru is dead. Thanks goodness.

According to the federal law of my country, quotes of this certain media cannot be accused of plagiarism, thus your argument is null, and i am not guilty by definition. If you think this is by law counts as plagiarism, add pictures that prove this please. Documentary evidence beats all other types of evidence and that’s why it’s the gold standard.
